on:
  pull_request:
    branches:
      - "18.0*"
  push:
    branches:
      - "18.0"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Install
        run: ./task install
      - name: Version
        run: ./task version
      - name: Test
        run: ./task test
